### ISSUE TITLE
Learning Resources for housing first programs

### ISSUE THREAD

**Issue by ericelliott** [jshomes/jshomes.org#2]
## Update - Discussion Moved!

We've created a new [learning-resources](https://github.com/jshomes/learning-resources) repository. All discussion about learning resources should be submitted there as Pull Requests or issues. Thanks everybody!

## Old stuff:

* [Learn JavaScript Essentials](https://medium.com/javascript-scene/learn-javascript-b631a4af11f2) for all skill levels
* [JS Dares](http://www.jsdares.com/) Game programming resources for kids and beginners

**Comment by lolptdr** [comment]
* [Javascript Patterns by Shi Chuan](http://shichuan.github.io/javascript-patterns/) JS programming patterns and antipatterns
* [You Don't Know JS](https://github.com/getify/You-Dont-Know-JS) Kyle Simpson's books deep-diving into the core mechanisms of JavaScript
* [Eloquent JavaScript](http://eloquentjavascript.net/) Marijn Haverbeke's introduction to JavaScript
* [CodeCombat](https://codecombat.com/) for all ages, especially children wanting to play games while learning programming, currently in JavaScript

**Comment by ericelliott** [comment]
Thanks!

**Comment by 1Marc** [comment]
I'd donate [Frontend Masters](https://FrontendMasters.com) licenses.

**Comment by ericelliott** [comment]
Marc, that's amazing. That's going to help a lot of people.

**Comment by Elfoslav** [comment]
http://www.codermania.com/ - Learn to code interactively, for now just JavaScript. Later HTML & CSS.

**Comment by ericelliott** [comment]
Thanks!

**Comment by davidhund** [comment]
http://humanjavascript.com/
http://eloquentjavascript.net/
http://jsbooks.revolunet.com/

**Comment by ericelliott** [comment]
Thanks David! =)

**Comment by csrobinson86** [comment]
http://www.sitepoint.com/javascript/raw-javascript/ - Always has good specific articles.
http://gymnasium.aquent.com/catalog - Video Course on JS fundamentals (4 hours long)
https://www.udacity.com/course/javascript-basics--ud804 - Video Course on JS Basic

**Comment by ericelliott** [comment]
Thanks! =)

**Comment by csrobinson86** [comment]
Eric - this resource more about the browser in-depth.  Really the best resource I have found in learning more about the behind the scenes work of the browser. 
http://www.html5rocks.com/en/tutorials/internals/howbrowserswork/#Render_tree_construction

**Comment by ericelliott** [comment]
Amazing suggestions, everybody! Let's start turning these into a Markdown document using the README file in the new [learning-resources](https://github.com/jshomes/learning-resources) repository. We'll close this issue once that work gets underway and move all future discussion on this topic to that repo.
